### ISSUE TITLE
[Tracking] vundle plugin issues

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#4306]
These issues and PRs need to be triaged to know which ones to pull. 

- [x] #3021: Clean up and add new vundle commands
- [x] #4145: Updating Vundle.vim url and path
- [x] #4281: Already installed vundle is not detected by vundle plugin
