### ISSUE TITLE
[Tracking] gradle plugin issues

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#4307]
- [x] #3661: Fix invocation of gradlew
- [x] #3859: gradle plugin: also list tasks in subprojects
- [x] #4166: not in the path gradlew support
