### ISSUE TITLE
[Tracking] docker issues

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#4308]
- [x] #3520: lxc-docker support (docker.io error)
- [x] #2411: Updated docker plugin to use Docker container names instead of hashes.
- [x] #2733: Docker plugin: merge with upstream's vendorized version
- [x] #2803: [docker plugin]: would be nice if it also completed image names in addition to image ids
- [x] #3037: [docker plugin] Add support for containers names and stopped containers
- [x] #3243: Updated autocomplete for Docker version 1.3
- [x] #3268: Added docker 1.3 new commands to compdef
- [x] #3438: OSX docker plugin not autocomplete
- [x] #4311: Update docker-compose plugin to latest version of the original script
- [x] #3289: Add docker useful alias
- [ ] #4054: Added useful docker aliases
- [x] #4148: Get docker ip

**Comment by scic** [comment]
+1

**Comment by leifcr** [comment]
@mcornella  #3243 should be replaced with #5060

**Comment by leifcr** [comment]
#4311 can be removed, as #5215 is merged

**Comment by leifcr** [comment]
#4148 has been closed
