### ISSUE TITLE
[Tracking] closable issues

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#4309]
- [x] #2416: no response; seems fixed
- [x] #2666: support provided, lack of response
- [x] #2692: fixed
- [x] #2696: seems fixed, no response
- [x] #2967: won't implement (at least for now)
- [x] #3021: obsoleted by #4268 
- [x] #3051: won't support zsh version
- [x] #3129: no response
- [x] #3193: unnecessary, polluted PR
- [x] #3350: lack of response
- [x] #3531: presumably solved, original poster unresponsive
- [x] #3557: obsoleted by #4099
- [x] #3624: obsoleted by #4268
- [x] #3643: removes what is a feature of the kolo theme
- [x] #3645: lack of response
- [x] #3656: wontfix; current behavior looks intentional
- [x] #3666: obsoleted by #3731
- [x] #3672: obsoleted by #4099
- [x] #3832: obsoleted by #4268
- [x] #3879: won't implement; polluted PR from master branch
- [x] #3895: support given
- [x] #4043: obsoleted by #4342 
- [x] #4065: yet another case of wrong symbols for powerline themes
- [x] #4048: fixed in #4230 by yourself @mcornella, as you said in #4048 (comment)
- [x] #4144: obsoleted by #4342 and #4349
- [x] #4157: seems fixed, no response
- [x] #4179: seems to be solved for the time being
- [x] #4206: won't implement
- [x] #4265: solved
- [x] #4281: obsoleted by #4268
- [x] #4295: lack of response (even 20 minutes after :disappointed:)
- [x] #4297: obsoleted by #4342
- [x] #4400: solved by #4337
- [x] #4405: question answered
- [x] #4477: won't implement

**Comment by apjanke** [comment]
How about

- [ ] #3531: looks resolved by fixing user locale, no recent response

**Comment by mcornella** [comment]
Added!

**Comment by apjanke** [comment]
- [ ] #3879: won't implement; polluted PR from `master` branch

**Comment by mcornella** [comment]
Okie dokie!

**Comment by apjanke** [comment]
[ ] #4405: question answered

**Comment by mcornella** [comment]
Done

**Comment by apjanke** [comment]
- [ ] #3656: wontfix; current behavior looks intentional

**Comment by mcornella** [comment]
done

**Comment by apjanke** [comment]
- [ ] #4157: seems fixed, no response

**Comment by ncanceill** [comment]
- [ ] #4048: Fixed in #4230 by yourself @mcornella, as you said in https://github.com/robbyrussell/oh-my-zsh/issues/4048#issuecomment-136826150

Awesome job, by the way!

**Comment by mcornella** [comment]
Added. This time it won't take long before they're closed :grin:

**Comment by mcornella** [comment]
Ok, that should be all. From now on, no more closing-issues lists! :blush:

**Comment by apjanke** [comment]
Couple more?
- [ ] #3843: no response; seems off-topic for OMZ
- [ ] #3830: no response; user configuration?
- [ ] #3129: no recent response

**Comment by mcornella** [comment]
done

**Comment by apjanke** [comment]
Couple more:

- [ ] #4105: no new themes
- [ ] #4062: no new themes

**Comment by apjanke** [comment]
- [ ] #4494: no response, looks answered.

**Comment by mcornella** [comment]
All done
