### ISSUE TITLE
[Tracking] meteor plugin issues

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#4327]
- [x] #4280: "meteor add-platform" & "meteor remove-platform" for meteor plugin
- [x] #4321: Meteor plugin needs a reboot
- [x] #3428: add new meteor commands
- [x] #3767: meteor plugin updated
- [x] #4126: Create meteor.plugin.zsh
- [x] #4538: Meteor-1-2 arguments update

**Comment by aayushkapoor206** [comment]
:+1:
