### ISSUE TITLE
[Tracking] SSH completion

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#4345]
Issues related to completion for `ssh` and related commands.

##  Issues  ##

- [ ] #4257 – common-aliases plugin configures zsh host completion
- [ ] #4162 – Request: tmux-cssh completion
- [X] #4101 – How to get host completion working for a new command?
- [X] #3229 – Behavior change after OMZ reverted to Zsh's hosts completion (2602)
- [X] #2945 – scp/rsync completion failure with remote globbing
- [ ] #2737 – Prefers /etc/hosts entries
- [ ] #2414 – Issue with ssh_config hosts completion (using OMZ's completion)
- [ ] #2288 – ssh_config host completion fails
- [ ] #1337 – "Auto-complete fails on SSH?"
- [X] #886 – Request: ssh_config host completion
- [X] #42 – known_hosts completion not working

##   Pull Requests  ##

- [ ] #3321 – tmux-cssh completion plugin
- [ ] #2707 – Add ssh_config host completion in new `ssh` plugin
- [X] #2702 – Add ssh_config host completion in new `ssh` plugin (dupe)
- [X] #2602 – Revert to Zsh's own default hosts completion
- [X] #2489 – Remove brackets from URLs in known_hosts
- [X] #2361 – Re-enable completion of user names
- [X] #2109 – Improve ssh known_hosts parsing
- [X] #1964 – Make ssh completion more configurable
- [X] #1498 – Dupe of 2602 (Revert to Zsh's own hosts completion)
- [X] #1343 – `scp` completion fails
- [X] #1265 – Fix typo in ssh completion
- [X] #1009 – Use ssh_config for host completion
- [X] #768 – Include global `/etc/ssh_known_hosts` in host completion
- [X] #690 – Add ssh_config parsing for host completion
- [X] #668 – Ignore port info from known_hosts
- [X] #127 – Completion improvements

###   ssh_config hosts  ###

A lot of these have to do with hosts defined in the `~/.ssh/config` and `/etc/ssh_config` files not showing up as options for completion. Zsh's own `_ssh` completion definition has code that reads hosts from `~/.ssh/config`, so it seems like they intend for it to be there by default. But it's not showing up for a lot of people, me included. We need to figure this out, to avoid thrashing on this topic.

**Comment by moul** [comment]
You can check #4162 and #2707

**Comment by apjanke** [comment]
#4162 and #2707 look like they're still open (though #4162 has an associated PR merged). I'd rather wait until they get closed out before checking them off.

**Comment by moul** [comment]
Sorry I meant #4162 (now closed) and #3321 instead of #2707 

Both are now closed :)

**Comment by EugenMayer** [comment]
One of the reasons hosts do not show up is known_hosts - if you delete it, a lot more hosts will be shown for config - i guess the keyword search is limited to a specific number of hits and probably parses known_hosts first, now showing the ssh/config ones at all

**Comment by robbyrussell** [comment]
Gonna close this older idea
