### ISSUE TITLE
[Tracking] install script related issues

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#4355]
**By topic:**

#### Backup of zshrc and default shell

- [ ] #2499: Some minor alteration concerning `.zshrc.pre-oh-my-zsh`
- [ ] #3447: oh-my-zsh uninstall.sh issues - switch back to bash is unsatisfactory
- [ ] #4355: just append the loading of OMZ to the zshrc file, leaving the rest of the file unchanged.
- [ ] #4391: installer: use timestamped backups to preserve all old zshrcs
- [ ] #4261: Prevent shell change during setup
- [ ] #4390: Please, oh please, ask, or at least warn, about overwriting ~/.zshrc on installation PR

#### `$PATH` management

- [ ] #2586: install.sh: `PATH=` with no `$PATH` inside
- [ ] #2589: Respect original PATH definitions on install
- [ ] #1359: Do not force PATH in the installer

#### Installed zsh check

- [ ] [#4818](https://github.com/robbyrussell/oh-my-zsh/issues/4818#issuecomment-178106951): installer doesn't check if the zsh obtained from `/etc/shells` exists

#### Non-interactive install

- [ ] #5002: add a way to not launch zsh after finishing

#### Other

- [ ] #3648: Installer: add ability to install from forked repos
- [ ] #4393: [Discuss] What should installer behavior be, esp wrt launching new shells?

**Comment by apjanke** [comment]
Issues:
- [ ] #3588: Installer fails on cygwin with git and chsh errors  
- [ ] #3447: oh-my-zsh uninstall.sh issues - switch back to bash is unsatisfactory  
- [ ] #3317: oh my zsh fresh install issue syntax error line 48 plugins=(git)   (dupe but still open?)
- [ ] #2586 install.sh: `PATH=` with no `$PATH` inside  
- [ ] #2499: Some minor alteration concerning .zshrc.pre-oh-my-zsh  


PRs:
- [ ] #3664: installer: Use printf and terminfo for portability  
- [ ] #3648: Installer: add ability to install from forked repos  
- [ ] #3646: Add Cygwin support to installer.
- [ ] #2589: Respect original PATH definitions on install

**Comment by apjanke** [comment]
Closed stuff with important discussions:
- [ ] #1359: Do not force PATH in the installer

**Comment by mcornella** [comment]
updated

**Comment by apjanke** [comment]
Cool. Deleted redundant comments.

**Comment by apjanke** [comment]
- [ ] #4390: Please, oh please, ask, or at least warn, about overwriting ~/.zshrc on installation

**Comment by apjanke** [comment]
- [ ] #4404:  install.sh doesn't work on FreeBSD
- [ ] #4376: install.sh fails if tput isn't available

**Comment by mcornella** [comment]
Done

**Comment by luislobo** [comment]
https://github.com/robbyrussell/oh-my-zsh/issues/5002

**Comment by mcornella** [comment]
Tracking is now done on #5169. Closing.
