### ISSUE TITLE
[Tracking] atom plugin

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#4356]
### Issues:
- [ ] #4144: Atom plugin: problems with Linux and Windows
- [ ] #4297: atom plugin not working on ubuntu

### Pull requests:
- [ ] #3193: Update alias of for Atom
- [ ] #4043: Adds ubuntu/linux support to atom plugin
- [ ] #4342: Fix Atom Plugin for Linux Users
- [ ] #4349: Fixed atom plugin for cygwin users

We need to _a)_ either delete the atom plugin (`$PATH` should be sufficient), _or_ _b)_ make it platform agnostic.

**Comment by robobenklein** [comment]
https://github.com/robbyrussell/oh-my-zsh/pull/4448 Fixes issue in comments on https://github.com/robbyrussell/oh-my-zsh/commit/953e4d892631f93e31cfdfb72199fb8f413c6b49#commitcomment-13393648

**Comment by robobenklein** [comment]
Atom plugin has been removed in https://github.com/robbyrussell/oh-my-zsh/commit/0516a39dec64568f6db194d143a0ae2969c3cf9b

This issue should be closed.
