### ISSUE TITLE
Refactor installer script

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#5123]
- [ ] Fix check for installed zsh
- [ ] Don't force `$PATH` in the installer
- [ ] Better zshrc file mangling
- [ ] Allow non-interactive install
- [ ] Other stuff?
